import os

AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN = os.getenv("AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN", "")
AZURE_DEVOPS_ORGANIZATION_NAME = os.getenv("AZURE_DEVOPS_ORGANIZATION_NAME", "")
AZURE_DEVOPS_PROJECT_NAME = os.getenv("AZURE_DEVOPS_PROJECT_NAME", "")
